var reporting_password = "password";

use reporting
db.auth({ user: "reporting", pwd: (reporting_password) })
db.util_cisco_expressway_license.insertOne({"time_stamp": "2016-01-1T00:00:00", "device_serial": "AAAAAAAA", "device_name": "DUMMY", "traversal_in_use": 0, "traversal_limit": 100, "non_traversal_in_use": 0, "non_traversal_limit": 100, "current_registrations": 0, "concurrent_calls": 0, "record_type": "util_cisco_expressway_license", "record_key": "AAAAAAAA_20160101000000"})
db.util_cisco_expressway_license.insertOne({"time_stamp": "2016-01-1T00:05:00", "device_serial": "AAAAAAAA", "device_name": "DUMMY", "traversal_in_use": 0, "traversal_limit": 100, "non_traversal_in_use": 5, "non_traversal_limit": 100, "current_registrations": 0, "concurrent_calls": 0, "record_type": "util_cisco_expressway_license", "record_key": "AAAAAAAA_20160101000500"})
db.util_cisco_expressway_license.insertOne({"time_stamp": "2016-01-1T00:10:00", "device_serial": "AAAAAAAA", "device_name": "DUMMY", "traversal_in_use": 0, "traversal_limit": 100, "non_traversal_in_use": 10, "non_traversal_limit": 100, "current_registrations": 0, "concurrent_calls": 0, "record_type": "util_cisco_expressway_license", "record_key": "AAAAAAAA_20160101001000"})
db.util_cisco_expressway_license.insertOne({"time_stamp": "2016-01-1T00:15:00", "device_serial": "AAAAAAAA", "device_name": "DUMMY", "traversal_in_use": 0, "traversal_limit": 100, "non_traversal_in_use": 15, "non_traversal_limit": 100, "current_registrations": 0, "concurrent_calls": 0, "record_type": "util_cisco_expressway_license", "record_key": "AAAAAAAA_20160101001500"})
db.util_cisco_expressway_license.insertOne({"time_stamp": "2016-01-1T00:20:00", "device_serial": "AAAAAAAA", "device_name": "DUMMY", "traversal_in_use": 0, "traversal_limit": 100, "non_traversal_in_use": 5, "non_traversal_limit": 100, "current_registrations": 0, "concurrent_calls": 0, "record_type": "util_cisco_expressway_license", "record_key": "AAAAAAAA_20160101002000"})
db.util_cisco_expressway_license.insertOne({"time_stamp": "2016-01-1T00:25:00", "device_serial": "AAAAAAAA", "device_name": "DUMMY", "traversal_in_use": 0, "traversal_limit": 100, "non_traversal_in_use": 30, "non_traversal_limit": 100, "current_registrations": 0, "concurrent_calls": 0, "record_type": "util_cisco_expressway_license", "record_key": "AAAAAAAA_20160101002500"})